### ISSUE TITLE
Nothing in Read-Me

### ISSUE THREAD

**Issue by Seanmclem** [cwoolum/capacitor-in-app-purchase#1]
Hi, The prospect of a Capacitor IAP Plugin is really great. Everything else seems to be poorly supported cordova plugins. So I'm excited to try out yours, but there's no documentation. 

What state is it in? Most things work? Could you provide any basic usage instructions? Otherwise I'd just be combing through the Typings and hoping there's nothing else to configure

**Comment by cwoolum** [comment]
Hi, Unfortunately i had just barely gotten started on it but ended up having to drop it. I had barely done anything more than create the interfaces. I don't have a timeline for completion or when I can pick this back up but I'll update the readme to avoid confusion.
